# 线上配置文件
# @author <a href="https://github.com/liyupi">程序员鱼皮</a>
# @from <a href="https://code-nav.cn">编程导航</a>
server:
  port: 8101
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.5.165.92:3306/mianshiya
    username: mianshiya_user
    password: 1433223@Mysql
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: 121.5.165.92
    port: 6379
    timeout: 5000
    password: 1433223@Redis
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: root
    password: 123456
